name: 'OpenTofu setup and plan'
on:
  pull_request: 
    types: [opened, synchronize, reopened]
jobs: 
    opentofu-setup-and-plan:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout Code 
        uses: actions/checkout@v4
      - name: Setup OpenTofu 
        uses: opentofu/setup-opentofu@v1
      - run: cd eks && tofu init
      - name: OpenTofu fmt
        run: tofu fmt -check
      - name: OpenTofu plan
        run: cd eks && tofu plan --var-file=env/dev/dev.tfvars