name: 'OpenTofu setup and plan'
on:
  pull_request: 
    types: [opened, synchronize, reopened]
jobs: 
    opentofu-setup-and-plan:
      runs-on: ubuntu-latest
      permissions:
        id-token: write
        contents: read
      steps:
      - name: Checkout Code 
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::590183739523:role/opentofu-role
          role-session-name: GitHubActionsOpenTofuSession
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
      - name: Setup OpenTofu 
        uses: opentofu/setup-opentofu@v1
      - run: cd eks && tofu init
      - name: OpenTofu fmt
        run: tofu fmt -check
      - name: OpenTofu plan
        run: cd eks && tofu plan --var-file=env/dev/dev.tfvars